/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ladderGame;

import ladderGame.ladder.LadderGame;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;

public class AppTest {

    /*
    *   발판이 연속해서 있는 경우가 있는지 테스트하는 메소드
    * */
    @Test
    @DisplayName("Line Test")
    public void lineTest() {
        // given
        Random random = new Random();
        List<String> playersTest = new ArrayList(10);
        List<String> result = new ArrayList(10);
        int height = random.nextInt(10);

        for(int i = 0; i < random.nextInt(10); i++){
            playersTest.add("p");
            result.add("r");
        }
        LadderGame classUnderTest = LadderGame.of(playersTest, result, height);

        for(int i = 0; i < height ; i++) { // ?
            // when ..?
            List<Boolean> pointsTest = classUnderTest.getLadder().get(i).getPoints();

            // then
            for(int j = 0; j < playersTest.size() - 1; j++) {
                Assertions.assertFalse(pointsTest.get(j) & pointsTest.get(j+1));
            }
        }
    }


}
