/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ladderGame;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        GameStarter classUnderTest = new GameStarter();
      //  assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
