/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.w1.ladder_game;

import java.util.List;

import be.w1.ladder_game.model.Ladder;
import be.w1.ladder_game.model.Player;
import be.w1.ladder_game.view.OutputView;
import be.w1.ladder_game.controller.LadderController;
import be.w1.ladder_game.view.InputView;

public class App {

    public static void main(String[] args) {
        InputView inputView = new InputView();
        OutputView outputView = new OutputView();

        String playersName = inputView.getPlayersName();
        int ladderHeight = inputView.getLadderHeight();

        LadderController ladderController = new LadderController(playersName, ladderHeight);

        Ladder ladder = ladderController.getLadder();
        List<Player> players = ladderController.getPlayers();

        outputView.printPlayers(players);
        outputView.printLadder(ladder);
    }
}

