/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.w1.ladder_game;

import static org.hamcrest.MatcherAssert.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.instanceOf;
import static org.hamcrest.MatcherAssert.assertThat;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

import be.w1.ladder_game.controller.LadderController;

class ControllerTest {
    @Test
    void ladderControllerConstructorSuccessTest() {
        List<Pair> testCaseList = new ArrayList<Pair>();
        testCaseList.add(new Pair("a,b,c,d,e", 5));
        testCaseList.add(new Pair("a,bc,def,ghij,klmno", 5));

        for (Pair testCase: testCaseList) {
            String playersName = testCase.getPlayersName();
            int ladderHeight = testCase.getLadderHeight();

            assertDoesNotThrow(() -> new LadderController(playersName, ladderHeight));
        }
    }
    @Test
    void ladderControllerConstructorFailTest() {
        List<Pair> testCaseList = new ArrayList<Pair>();
        testCaseList.add(new Pair("a,bc,def,ghij,klmnop", 5));
        testCaseList.add(new Pair("a,b,c,d,e", 0));

        for (Pair testCase: testCaseList) {
            String playersName = testCase.getPlayersName();
            int ladderHeight = testCase.getLadderHeight();

            assertThrows(RuntimeException.class, () -> new LadderController(playersName, ladderHeight));
        }
    }
}
